### ISSUE TITLE
[アプリ]ログイン機能を作成

### ISSUE THREAD

**Issue by toyoshin5** [jphacks/SP_2303#1]
Firebaseを使ったログイン機能を実装しておきたい
参考:[#24 Flutter入門講座 Firebase Auth編](https://www.youtube.com/watch?v=KsixooHekJE&t=619s&pp=ygURZmx1dHRlciBmaXJlYmFzZSA%3D)

**Comment by karintou8710** [comment]
アプリ名と詳細の文章が決まったら修正する
