### ISSUE TITLE
[アプリ]育成画面を作成する

### ISSUE THREAD

**Issue by toyoshin5** [jphacks/SP_2303#6]
育成画面を作成したい。
ユーザ名,レベル,累計経験値,キャラクターなどなどが表示される

**Comment by usatyo** [comment]
- デザインのみ完成
- ロジックは未実装


<img width="414" alt="image" src="https://github.com/jphacks/SP_2303/assets/63779824/0d0107f4-cf62-427f-9f41-9ce1ef510721">
